# Config file for automatic testing at travis-ci.org

language: python

python:
    - "2.7"

env:
    global:
        - GAE_VERSION=1.9.24
        - PYTHONPATH=$PYTHONPATH:$PWD/vendor/google_appengine
    
before_script:
    - wget -P vendor -nv https://storage.googleapis.com/appengine-sdks/featured/google_appengine_${GAE_VERSION}.zip
    - unzip -q -d vendor vendor/google_appengine_${GAE_VERSION}.zip

install:
    # May not need this now that GAE out of venv 20150801
    # - ln -s $PWD/gae_lib.pth $(python -c 'import sys; import os; print(os.path.join(sys.prefix, "lib", "python" + sys.version[:3], "site-packages"))')
    - pip install -t lib -r requirements.txt
    - pip install -r dev-requirements.txt
    - pip install tox

# command to run tests, e.g. python setup.py test
script: tox
